### PR TITLE
update copyright year

### PR DESCRIPTION
**Pull request by enoch85**
Tested on localhost and it works. This will automatically update the copyright year instead of manually have to change it every year.

Please SQUASH the commits before merging.

**MIT Licensed**

### CODE REVIEW

**Comment by enoch85** [comment]
ping @LukePulverenti

**Comment by LukePulverenti** [comment]
Hi, thanks for the contribution. The problem here is we'd prefer to stay with static html over php. Everytime we update the website we have a (rudimentary) build process that handles template replacement and we could easily handle making the year dynamic with that.

What we really need in the near future though is an all new website designed with tools that are made for static output, and at that point everything will be much easier to work with. The current website is just a static export of what we had before, and that's why there's a fair amount of duplication across the files. Thanks.

**Comment by enoch85** [comment]
@LukePulverenti I understand. 

I found your website through a link in a forum and thought "2015?!" It gives a bad impression and an impression of that you don't maintain your stuff. Looking at the Github repo made me think otherwise though.

Feel free to close, but please fix this issue asap for your own sake. Or go with PHP and merge this PR.

Thanks.

**Comment by LukePulverenti** [comment]
Thanks, we'll fix them.

**Pull request closed without merging**
